
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/var/www/html/stream-webrtc/google-cloud-sdk/path.bash.inc' ]; then source '/var/www/html/stream-webrtc/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/var/www/html/stream-webrtc/google-cloud-sdk/completion.bash.inc' ]; then source '/var/www/html/stream-webrtc/google-cloud-sdk/completion.bash.inc'; fi
